# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

  
steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y terraform
    terraform version
  displayName: Install Terraform
- task: PipelineTerraformInstaller@1
  inputs:
    terraformVersion: '1.13.5'


- task: PipelineTerraformTask@5
  displayName: Terraform Init
  inputs:
    command: 'init'
    allowTelemetryCollection: false

- task: PipelineTerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Azure subscription 1(70afab57-e956-4f72-af85-7a5e7b815620)'



